# Copyright 2016 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Yages example API configuration.
#
#

# The configuration schema is defined by service.proto file
# https://github.com/googleapis/googleapis/blob/master/google/api/service.proto
type: google.api.Service
config_version: 3

#
# Name of the service configuration.
#
name: echo.endpoints.grpc-field-test.cloud.goog

#
# Endpoints availaable in the service
#
endpoints:
- name: echo.endpoints.grpc-field-test.cloud.goog 
  target: "35.229.70.115"

#
# API title to appear in the user interface (Google Cloud Console).
#
title: YAGES gRPC API
apis:
- name: yages.Echo
- name: grpc.reflection.v1alpha.ServerReflection

#
# API usage restrictions.
#
usage:
  rules:
  ### allow public access to all API's
  - selector: "*"
    allow_unregistered_calls: true

  ### only reflection can be called without an API Key
  #- selector: yages.Echo.Ping
  #  allow_unregistered_calls: false
  #- selector: grpc.reflection.v1alpha.ServerReflection.ServerReflectionInfo
  #  allow_unregistered_calls: true
